name: Weekly Orders Export
permissions:
  contents: read

on:
  repository_dispatch:
    types: [export_orders]
  workflow_dispatch: # Manual trigger from GitHub UI

jobs:
  export:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Export orders
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BUSINESS_SLUG: ${{ secrets.BUSINESS_SLUG }}
        run: node export-orders.js
